### PR TITLE
VL maps

### PR DESCRIPTION
**Pull request by makella**
Almost done

still have to:
- [ ] add animation examples
- [ ] prepare descriptions for meeting

### CODE REVIEW

**Comment by VictorVelarde** [comment]
@makella I checked the list of current vizs and they look pretty nice 👌 

The only concern that I have is that it is already a pretty long list (16 vizs), without considering those about animations that you want to add.

If we can't have a shorter list, maybe we could indicate somehow the most important / original / stylish ones.

From the current list, I specially like: ramps / clusters and buckets / viewport based styles / interp. & zoom range / anyone from classification methods (maybe pick just 1 and talk about others in 'comments') and Data driven color exp (bivariate). I also like Cordoba's, but imho the zoom is a bit far away.

Once you have the descriptions, please share them too.

**Review by VictorVelarde — COMMENTED** [review]
👍 They work fine and look really good. I just made a comment about its quantity

**Comment by makella** [comment]
hiii @VictorVelarde!

thanks for looking through! I know!! it has been super hard to pick and choose what to add. All of the examples are things they don't have that I saw on their roadmap so it is hard to choose! 

I took your advice and removed the st deviation and quantiles classification examples and kept in the manual (they mention in their roadmap they need more classification methods that's why i stuck those in.) related, the linear and log scale maps are another thing they mention that they need to add. 

i'm assuming we'll let them take a closer look at this, right? even if they don't go through all of the examples, maybe they will be useful for them to explore after the meeting.

with the animation examples, we have 17! sorry!! i actually am holding back from adding more! 

I think if we know whether or not they will be looking at them on their own time, will be helpful. Feel free to remove after you speak with the group Monday.

I think I'm going to replace Cordoba w/ NY City Buildings since they are larger and easier to see..,

map write-up coming next.

**Comment by makella** [comment]
keeping cordoba - i added a brighter color scheme that helps! 
something funny is happening with NYC where the filter works, but half of central park shows up... not happening in the editor or on other web maps of the same thing... anyway, in case you guys want to add that instead, here is the style

```
{
    id: 'animation_cumulative',
    name: 'Cumulative Animation',
    username: 'cartovl',
    dataset: 'mnmappluto',
    viz: `color: ramp(linear($yearbuilt,1900,2018),prism)
filter: $numfloors > 2 and animation(linear($yearbuilt,1900,2018), 20, fade(0.1, hold))
strokeWidth: 0
`,
    mapState: {
      latitude: 40.763723,
      longitude: -73.954400,
      zoom: 12
    }
},
```

**Pull request merged**
